# Generated by Django 5.0.14 on 2026-03-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='open_in_new_tab',
            field=models.BooleanField(default=True),
        ),
    ]
