# Generated by Django 5.0.14 on 2026-03-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_link_url_notification_open_in_new_tab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='link_url',
            new_name='action_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='open_in_new_tab',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
