# Generated by Django 5.0.14 on 2026-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_link_url_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='broadcast_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
