# Generated by Django 5.0.14 on 2026-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_broadcast_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='broadcast_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
